Make untar_chart and force mutually exclusive
It was found that having both `untar_chart` and `force`
parameters set in the helm_pull module caused error due to
helm behavior:

```
helm pull --untar oci://registry-1.docker.io/bitnamicharts/redis
Pulled: registry-1.docker.io/bitnamicharts/redis:24.1.2
Digest: sha256:33c967f89f5933e8ba789e0bde5fbf35b71e5a3957709420ce38dfef6bc58d18
Error: failed to untar: a file or directory with the name redis already exists
```